<?xml version="1.0"?>

<robot>
	<gazebo>
		<plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
			<alwaysOn>false</alwaysOn>
			<legacyMode>false</legacyMode>
			<updateRate>20</updateRate>
			<leftJoint>left_wheel_joint</leftJoint>
			<rightJoint>right_wheel_joint</rightJoint>
			<wheelSeperation>${wheel_seperation}</wheelSeperation>
			<wheelDiameter>${wheel_radius*2}</wheelDiameter>
			<torque>20</torque>
			<commandTopic>/simbot/base_controller/cmd_vel</commandTopic>
			<odometryTopic>/simbot/base_controller/odom</odometryTopic>
			<odometryFrame>odom</odometryFrame>
			<robotBaseFrame>base_footprint</robotBaseFrame>
		</plugin>
	</gazebo>

	<gazebo reference="sensor_laser">
		<sensor type="ray" name="head_hokuyo_sensor">
			<pose>0 0 0 0 0 0</pose>
			<visualize>false</visualize>
			<update_rate>20</update_rate>
			<ray>
				<scan>
					<horizontal>
						<samples>1440</samples>
						<resolution>1</resolution>
						<min_angle>-3.14159</min_angle>
						<max_angle>3.14159</max_angle>
					</horizontal>
				</scan>
				<range>
					<min>0.10</min>
					<max>30.0</max>
					<resolution>0.01</resolution>
				</range>
				<noise>
					<type>gaussian</type>
					<mean>0.0</mean>
					<stddev>0.01</stddev>
				</noise>
			</ray>
			<plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
				<topicName>/simbot/laser_scan/scan</topicName>
				<frameName>sensor_laser</frameName>
			</plugin>
		</sensor>
	</gazebo>
</robot>
